### ISSUE TITLE
RFE: Avoid cluttering $HOME, move config files/data to their appropriate place.

### ISSUE THREAD

**Issue by devwatchdog** [ayoisaiah/f2#13]
Short description:
f2 writes to $HOME/.f2

What is wrong with this?
If all programs would write to $HOME, one would end up with $HOME full of dot files/dirs. This not only leads to cutter, but makes it difficult for backup. There are also folks who manage their $HOME or part(s) of it with git. So if apps write non important stuff directly to $HOME, you can imagine how many changes git would report. One would also backup this stuff. Their exists a standard that defines where an application should save {config, temporary, cache,...} files. For more information have a look at XDG spec.

Solution:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html 

Go implementations of the the spec (random):
https://github.com/adrg/xdg
https://github.com/rkoesters/xdg

F2 version v1.6.7

**Comment by ayoisaiah** [comment]
Thank you for bringing this to my attention. I will ensure to fix this in the next release.

**Comment by ayoisaiah** [comment]
Fixed https://github.com/ayoisaiah/f2/commit/4eedf6b60839521dcf0996371bd86f92a79f971d
