### ISSUE TITLE
Binary releases since v1.7.0 missing licence

### ISSUE THREAD

**Issue by AulonSal** [ayoisaiah/f2#14]
The `linux_amd64` binary releases (only ones I checked) do not have a licence anymore:
- [v1.7.1](https://github.com/ayoisaiah/f2/releases/download/v1.7.1/f2_1.7.1_linux_amd64.tar.gz)
- [v1.7.0](https://github.com/ayoisaiah/f2/releases/download/v1.7.0/f2_1.7.0_linux_amd64.tar.gz)

[v1.6.7](https://github.com/ayoisaiah/f2/releases/download/v1.6.7/f2_1.6.7_linux_amd64.tar.gz) did include one, is this intended behaviour?

**Comment by ayoisaiah** [comment]
@AulonSal It's not an intentional change....it looks like Goreleaser failed to add the licence file to the archive due to the new Changelog file. I've explicitly added the licence to the config now so that it's always included for future releases.
