### ISSUE TITLE
"-e" option considers the last period in directory name as extension separator

### ISSUE THREAD

**Issue by nevermarine** [ayoisaiah/f2#16]
For example, if I have directory `test.dir.period` nested inside `test` directory, then running `f2 -ed -f '\.' -r ' ' test` returns this:
```
+----------------------+----------------------+--------+
|        INPUT         |        OUTPUT        | STATUS |
+----------------------+----------------------+--------+
| test/test.dir.period | test/test dir.period | ok     |
+----------------------+----------------------+--------+
```
And if I try to match the "extension" of the directory by running `f2 -ed -f 'period' -r 'full stop' test`:
` INFO  Failed to match any files`

Version: 1.7.2
OS: Arch Linux

**Comment by ayoisaiah** [comment]
Hi @nevermarine 

That's the expected behaviour. If you want to match both periods, you can remove the `-e` flag.

```
$ f2 -d -f '\.' -r ' ' test
+----------------------+----------------------+--------+
|        INPUT         |        OUTPUT        | STATUS |
+----------------------+----------------------+--------+
| test/test.dir.period | test/test dir period | ok     |
+----------------------+----------------------+--------+
```

**Comment by nevermarine** [comment]
Hi! 
Yes, I know, but if I have some files that also contain periods I want to scrap, I need to run f2 two times, one for files:
 `$ f2 -e -f '\.' -r ' ' test` 
and one for directories:
` $ f2 -D -f '\.' -r ' ' test`
It's not really a problem, but it is a bit unintuitive.

**Comment by ayoisaiah** [comment]
Thanks for the clarification. I see what you mean, and I think you're correct. Directory names don't have extensions so the `-e` flag should not affect them.

I've made the fix, and it will be released soon.
