### ISSUE TITLE
f2 phones home to Microsoft leaking my IP as an f2 user without consent when I run `f2 --version`

### ISSUE THREAD

**Issue by sneak** [ayoisaiah/f2#18]
Behavior reproduced in F2 version v1.7.2:

https://github.com/ayoisaiah/f2/blob/134ae1ec23ef74c8248c7b4b09035ca3d53a6d49/src/app.go#L149

# Steps to reproduce:

1. Run `f2 --version`.

# Observed behavior:

F2 phones home to Microsoft without consent, leaking my IP to Microsoft as a user of F2 (enabling tracking):

<img width="548" alt="Screen Shot 2022-02-01 at 21 56 20" src="https://user-images.githubusercontent.com/408977/152100802-162035e3-0bfe-4dde-a14b-c4432a5df274.png">

# Expected behavior:

The software would ask opt-in permission before leaking my usage activity and IP to giant multinationals.

**Comment by ayoisaiah** [comment]
Thanks for raising this issue. I will change the behavior so that it becomes opt-in henceforth.

**Comment by ayoisaiah** [comment]
Close via 681d6278d16bf2120fbeabde7c5096991e2f133e
