### ISSUE TITLE
[bug] (windows) open System Volume Information: Access is denied.

### ISSUE THREAD

**Issue by mo-han** [ayoisaiah/f2#2]
on windows os, when CWD is a drive root, do sth like `f2 -R -d -f x -r y` raise error `open System Volume Information: Access is denied.`
it seems like f2 is trying to access the special dir `System Volume Information` in every drive root, which is actually hidden and should be skipped / ignored by f2 (since the `--hidden, -H` option is not given)

**Comment by ayoisaiah** [comment]
The `--hidden` options is for dotfiles at the moment. But I will try to reproduce your issue and see how it can be resolved

**Comment by ayoisaiah** [comment]
@mo-han This bug is now fixed, please upgrade to v1.3.0. Feel free to reopen if you run into this issue again.
Thanks
