### ISSUE TITLE
Leading zeros

### ISSUE THREAD

**Issue by jsteltner** [ayoisaiah/f2#21]
I'm using 

f2 -f '(\w+) \((\d+)\).(\w+)' -r '$1-$2.$3'

and get

| ORIGINAL            | RENAMED           | STATUS |
| ************************************************ |
| 1528655011 (1).jpg  | 1528655011-1.jpg  | ok     |
| 1528655011 (10).jpg | 1528655011-10.jpg | ok     |

but I want for $2 leading zeros and 3 digits.

How I have to do it?

**Comment by ayoisaiah** [comment]
@jsteltner Unfortunately, that use case is currently not supported, but I will look to add it. You can look at https://github.com/ayoisaiah/f2/wiki/Indexing in the meantime if that will work for you.

**Comment by ayoisaiah** [comment]
![image](https://user-images.githubusercontent.com/13372163/156755336-9861b2ea-918a-46a7-88a5-4a939187095f.png)

This is what you're looking for right?

**Comment by jsteltner** [comment]
Yes, excactly !

**Comment by ayoisaiah** [comment]
I've [added this feature](https://github.com/ayoisaiah/f2/commit/8e801cb48faff879c8a606845f4361d43376f3e3) so it will be in the next release :)
