### ISSUE TITLE
Renaming mp3s fails on Windows if using ID3 tags.

### ISSUE THREAD

**Issue by Boggart** [ayoisaiah/f2#22]
Trying to rename a folder full of mp3 on Windows 10 using ID3 tags results in the following error for every file:
```The process cannot access the file because it is being used by another process.```
Using a file handle viewer, I was able to conclude that no processes actually had the files open and by trial and error, I discovered that it was the use of ID3 tags to rename it that was causing the error.
```f2 -r "{{id3.artist}} - {{id3.title}}{{ext}}" -x```

**Comment by ayoisaiah** [comment]
@Boggart Are you still experiencing this issue?

**Comment by ayoisaiah** [comment]
Closing this as I don't have enough info to investigate. Feel free to reopen if you run into this issue once again.

**Comment by Boggart** [comment]
Sorry for disappearing, I am actually still having this problem. I've even tried other mp3 files just in case it was a matter of having certain characters in the name but it does it for every mp3 file I've thrown at it. I'm running Windows 10 21H1 if that helps, I've tried disabling real-time virus protection in case it was opening the files to scan and causing a problem, but no luck there.

**Comment by ayoisaiah** [comment]
Thank you for coming back! That's a strange problem, but I will investigate for sure.

**Comment by ayoisaiah** [comment]
Thanks so much! I've been able to fix the problem https://github.com/ayoisaiah/f2/commit/badc4523dfd89550709647d791d501edc6fb5c42 and it will make the next release in a couple of days.

I forgot to close the file after reading the ID3 tag so that's why the renaming failed.
