### ISSUE TITLE
[feature request] Is it possible to add DateTimeOriginal time?

### ISSUE THREAD

**Issue by dennys** [ayoisaiah/f2#23]
I'm a newbie to use F2 and feel it's so fast and cool. I use it to rename my photos.
And is it possible to add DateTimeOriginal time?
It's the time of the shutter actuation (capture time), I think it's meaning ful for a photo rather than file create or change time.

**Comment by ayoisaiah** [comment]
Hi @denneys,

You can use the [built-in exif variables](https://github.com/ayoisaiah/f2/wiki/Built-in-variables#exif-variables) to access an image's capture time. Use `{{exif.dt.<token>}}` with an appropriate [date token](https://github.com/ayoisaiah/f2/wiki/Built-in-variables#date-tokens) as in:

```
f2 -f 'proraw.dng' -r '{{exif.dt.YYYY}}-{{x.dt.MMM}}-{{x.dt.DD}}_{{f}}{{ext}}'
```
