### ISSUE TITLE
How to batch pad 0 of number ?

### ISSUE THREAD

**Issue by jack6th** [ayoisaiah/f2#25]
Files in the current directory:   
1.txt 22.txt 333.txt    
1.txt -> 0001.txt
22.txt -> 0022.txt
333.txt -> 0333.txt
With another command line rename tool [nomino](https://github.com/yaa110/nomino):   
nomino -tp "([0-9]+).txt" "{:4}.txt"   
Since it is a very common task.    
How to do this with f2 ?

**Comment by ayoisaiah** [comment]
@jack6th Sure:

```
f2 -f '(.*).txt' -r '$1%04d'
```

```
┌─────────────────────────────┐
| ORIGINAL | RENAMED | STATUS |
| *************************** |
| 1.txt    | 0001    | ok     |
| 22.txt   | 0022    | ok     |
| 333.txt  | 0333    | ok     |
└─────────────────────────────┘
```

See: https://github.com/ayoisaiah/f2/wiki/Indexing

**Comment by jack6th** [comment]
Not works on Windows.

**Comment by ayoisaiah** [comment]
Are you using Command Prompt or powershell? Please use double quotes for the former
