### ISSUE TITLE
Dry option in simple mode

### ISSUE THREAD

**Issue by honzajde** [ayoisaiah/f2#26]
Provide an option to "dry run" the f2 command.

**Comment by ayoisaiah** [comment]
What do you mean? F2 is dry run by default except in simple mode.

**Comment by honzajde** [comment]
Yeah, except in simple mode - I was surprised it to work suddenly without asking for -f. There is undo that helped... I guess I need to use it in the correct mode then. It's just not the way I use it. I think with this kind of tools that people use from time to time you should not expect anyone remember such things like modes;) It's a great tool though.

**Comment by ayoisaiah** [comment]
Thanks for the suggestions! I could tweak simple mode a bit so it prompts you before making the changes, keeping with the spirit of the tool. And a way to specify not to be prompted in the future for those who can remember.

**Comment by ayoisaiah** [comment]
Closed by https://github.com/ayoisaiah/f2/commit/8c7defc116ce15822ff31c6dd31afe6a1d85e1b7
