### ISSUE TITLE
String functions usage enhancements

### ISSUE THREAD

**Issue by honzajde** [ayoisaiah/f2#27]
I would suggest couple of enhancements to this great tool!

1. allow string functions to be used on match groups, e.g.: `f2 '\b(.)' '{{$1.up}}'` 
2. allow string transformations to be used on built in variables: e.g.: `f2 '.*' '{{f.ti}}{{ext}}'`

**Comment by ayoisaiah** [comment]
Great suggestions! I can take a stab at expanding variable functionality this weekend

**Comment by ayoisaiah** [comment]
Implemented here https://github.com/ayoisaiah/f2/commit/f975e803829e0ef2e3187127195077d52df96198
Will include in the next release soon
