### ISSUE TITLE
Using regex capture group appended with underscore leads to erroneously named files

### ISSUE THREAD

**Issue by d-Rickyy-b** [ayoisaiah/f2#32]
Hi and thank you for creating this awesome tool!

I ran into an issue where f2 doesn't generate the desired output name when using regex capture groups together with an underscore.

### Steps to reproduce
I created a test directory with three test files. In there I tried to rename the `test1.txt` to `test_01.txt`.
```powershell
PS > touch test1.txt
PS > touch test2.txt
PS > touch test3.txt
PS > f2 -f '(.*)\d.txt' -r '$1_%02d{{ext}}'
```

### Expected result
I assumed that the files would get renamed to `test_01.txt`, etc. Something like this:

```
┌──────────────────────────────────┐
| ORIGINAL  | RENAMED     | STATUS |
| ******************************** |
| test1.txt | test_01.txt | ok     |
| test2.txt | test_02.txt | ok     |
| test3.txt | test_03.txt | ok     |
└──────────────────────────────────┘
```

### Actual result
Actually the tool is not happy about the `_` and does not insert the first capture group at all.
```
┌──────────────────────────────┐
| ORIGINAL  | RENAMED | STATUS |
| **************************** |
| test1.txt | 01.txt  | ok     |
| test2.txt | 02.txt  | ok     |
| test3.txt | 03.txt  | ok     |
└──────────────────────────────┘
```

The error becomes more obvious when using the following command: `f2 -V -f '(.*)\d.txt' -r '$1_a'`

```
┌──────────────────────────────────────┐
| ORIGINAL  | RENAMED | STATUS         |
| ************************************ |
| test1.txt |         | empty filename |
| test2.txt |         | empty filename |
| test3.txt |         | empty filename |
└──────────────────────────────────────┘
```

Without the underscore it works just fine `f2 -V -f '(.*)\d.txt' -r '$1 %02d{{ext}}'`
```
┌──────────────────────────────────┐
| ORIGINAL  | RENAMED     | STATUS |
| ******************************** |
| test1.txt | test 01.txt | ok     |
| test2.txt | test 02.txt | ok     |
| test3.txt | test 03.txt | ok     |
| test4.txt | test 04.txt | ok     |
└──────────────────────────────────┘
```

### Version
```
PS > f2 --version
f2 version v1.8.0
https://github.com/ayoisaiah/f2/releases/v1.8.0
```

Let me know if you need anything else in order to further investigate the issue.

Cheers,
Rico

**Comment by d-Rickyy-b** [comment]
Similarly there seems to be an issue with using capture groups directly in front of [index variables](https://github.com/ayoisaiah/f2/wiki/Indexing).

```
> f2 -V -f '(.*)\d.txt' -r '$1%02d{{ext}}'
┌───────────────────────────────────────────────────────────┐
| ORIGINAL  | RENAMED      | STATUS                         |
| ********************************************************* |
| test1.txt | test%02d.txt | overwriting newly renamed path |
| test2.txt | test%02d.txt | overwriting newly renamed path |
| test3.txt | test%02d.txt | overwriting newly renamed path |
| test4.txt | test%02d.txt | overwriting newly renamed path |
└───────────────────────────────────────────────────────────┘
```

**Comment by ayoisaiah** [comment]
Thanks for reporting this, I have been able to reproduce it.  I will investigate the problem and find a fix.

In the meantime, you can do something like this:

```shell
f2 -f '(.*)\d.txt' -r '$1 %02d{{ext}}' -f ' ' -r '_'
```

```
┌──────────────────────────────────┐
| ORIGINAL  | RENAMED     | STATUS |
| ******************************** |
| test1.txt | test_01.txt | ok     |
| test2.txt | test_02.txt | ok     |
| test3.txt | test_03.txt | ok     |
└──────────────────────────────────┘
```

**Comment by ayoisaiah** [comment]
@d-Rickyy-b The solution is to use `${1}`. 

Go uses `$name` or `${name}` to represent capture variables where `name` is a non-empty sequence of letters, digits, and underscores.

When you use something like `$1`, it refers to the submatch at index 1. When you use `$1_`, it tries to find a variable named `1_` that was captured like this `(?P<1_>...)` which does not exist leading to the empty string.

So if you want to avoid retain the use of indexes (`$1`) while appending letters, digits, and underscores to the captured variable, you need to use the full syntax: `${1}`:

```shell
f2 -f '(.*)\d.txt' -r '${1}_%02d{{ext}}'
```

```
┌──────────────────────────────────┐
| ORIGINAL  | RENAMED     | STATUS |
| ******************************** |
| test1.txt | test_01.txt | ok     |
| test2.txt | test_02.txt | ok     |
| test3.txt | test_03.txt | ok     |
└──────────────────────────────────┘
```

I hope this explains it a bit. You can read the [Expand docs](https://pkg.go.dev/regexp#Regexp.Expand) to learn more.

I will also update the docs with the next release to mention this behaviour.

**Comment by d-Rickyy-b** [comment]
Hi @ayoisaiah, thank you very much for the detailed answer, appreciate it!
Your solution works perfectly fine. Looking forward to the updated docs.

Have a great day and keep this project awesome :)
