### ISSUE TITLE
Currently filenames like `EP.1.v0.1080p.mp4` do not get sorted correctly

### ISSUE THREAD

**Issue by candrapersada** [ayoisaiah/f2#34]
Currently filenames like `EP.1.v0.1080p.mp4` do not get sorted correctly
(e.g. episode 11 right after episode 1). That is caused by the `.` in
front of the episode number, making it get sorted as if it were
decimals.

**Comment by ayoisaiah** [comment]
Thanks for opening this issue!

I've provided a "natural" sort that you can use in such cases:

![image](https://github.com/ayoisaiah/f2/assets/13372163/09e09695-aa31-4bf4-9db3-0efc6d484751)
