### ISSUE TITLE
question: search and replace file contents

### ISSUE THREAD

**Issue by gedw99** [ayoisaiah/f2#36]
wondering if this tool can do search and replace of segments within a file.

for example i need to do this to markdown files.

**Comment by ayoisaiah** [comment]
F2 only works for file names not file contents. You can use `sed` for that

**Comment by gedw99** [comment]
thanks will find a golang tool for it as i need cross platform

**Comment by ayoisaiah** [comment]
I believe https://github.com/chmln/sd is cross platform

**Comment by gedw99** [comment]
👍

**Comment by gedw99** [comment]
https://github.com/bitfield/script might be enough
