### ISSUE TITLE
test data is missing ?

### ISSUE THREAD

**Issue by gedw99** [ayoisaiah/f2#37]
https://github.com/ayoisaiah/f2/blob/master/f2_test/f2_test.go#L74 lists all the files that the test will use

but the testdata folder does not have all these.

**Comment by ayoisaiah** [comment]
@gedw99 Those files are autocreated before each test and deleted after each test. https://github.com/ayoisaiah/f2/blob/master/f2_test/f2_test.go#L104

**Comment by gedw99** [comment]
thanks
