### ISSUE TITLE
Installation and usage instructions for Termux/Android

### ISSUE THREAD

**Issue by d-Rickyy-b** [ayoisaiah/f2#39]
Hi there,

after I switched phones recently, all my "last modified" timestamps of my images were set to a wrong date which means images don't show up in the correct order. Now I wanted to use f2 to fix that issue. Sadly Windows does not allow command line access to the phone, so I checked alternatives and saw that you offer a termux/Android version.

Since I have never used external software with termux, I was a bit stuck. An entry in the wiki page for installation would probably help newcomers find what they need. Also it would be a nice addition to the otherwise already excellent wiki you have for this project.

Looking forward to hearing from you.

Rico

PS: I solved the initial issue with the timestamps as follows:

```
$ for name in IMG_[0-9]*.mp4; do touch -t ${name:4:8}${name:13:4}.${name:17:2} "$name"; done
$ for name in VID_[0-9]*.mp4; do touch -t ${name:4:8}${name:13:4}.${name:17:2} "$name"; done
```

**Comment by ayoisaiah** [comment]
Thank you for raising this! Android instructions have been added now :)
