### ISSUE TITLE
Program:Win32/Wacapew.C!ml 

### ISSUE THREAD

**Issue by graphixillusion** [ayoisaiah/f2#4]
According to virustotal, the new 1.2.0 version is seen by Microsoft as Program:Win32/Wacapew.C!ml.

https://www.virustotal.com/gui/file/22448970adabb868aa40d229efffdc8aa2d364ef630355526f96c870ee4121fa/detection

**Comment by ayoisaiah** [comment]
Not sure what is going on here but I'm investigating

**Comment by graphixillusion** [comment]
maybe a false positive: here's the new detections list for version 1.2.1

https://www.virustotal.com/gui/file/0649966a91ebc3b53a9fdb2311328e50fbf7d456003a2be6cdc459e0d7fcb363/detection

only 2/67. Microsoft doesn't detect anything now.
