### ISSUE TITLE
not working for me!

### ISSUE THREAD

**Issue by teodias** [ayoisaiah/f2#43]
Hi there,

I found your app tonight while testing multiple cli regex batch renaming tools.

In the first place it was very convincing but it didn't work for me.

I have file names like:
Rechnung_01_2023_30071007000721.pdf
Rechnung_02_2023_30071007000721.pdf
Rechnung_03_2023_30071007000721.pdf
Rechnung_04_2023_30071007000721.pdf
Rechnung_05_2023_30071007000721.pdf

I tested my regex on https://regex101.com/ for matching "(\d{2})_(\d{4})" and replacing it by "$2_$1".

I'm sure this is a very basic operation, but I don't know why your app doesn't produce the expected output?!

My command line looks like:
```
D:\!data\documents\telekom 2022-10-10\2023>"c:\!data\pc-game\Desktop\f2_1.9.0_windows_amd64.tar\f2.exe" -f "(\d{2})_(\d{4})" -r "$2_$1"
```

and the result is missing $2:
```
┌───────────────────────────────────────────────────────────────────────────────┐
| ORIGINAL                            | RENAMED                        | STATUS |
| ***************************************************************************** |
| Rechnung_01_2023_30071007000721.pdf | Rechnung_01_30071007000721.pdf | ok     |
| Rechnung_02_2023_30182074000721.pdf | Rechnung_02_30182074000721.pdf | ok     |
| Rechnung_03_2023_30289101000721.pdf | Rechnung_03_30289101000721.pdf | ok     |
| Rechnung_04_2023_30399641000721.pdf | Rechnung_04_30399641000721.pdf | ok     |
| Rechnung_05_2023_30508276000721.pdf | Rechnung_05_30508276000721.pdf | ok     |
| Rechnung_06_2023_30731561000721.pdf | Rechnung_06_30731561000721.pdf | ok     |
└───────────────────────────────────────────────────────────────────────────────┘
```

The command line:
```
D:\!data\documents\telekom 2022-10-10\2023>"c:\!data\pc-game\Desktop\f2_1.9.0_windows_amd64.tar\f2.exe" -f "(\d{2})_(\d{4})" -r "$2-$1"
```

works well with the expected output:
```
┌────────────────────────────────────────────────────────────────────────────────────┐
| ORIGINAL                            | RENAMED                             | STATUS |
| ********************************************************************************** |
| Rechnung_01_2023_30071007000721.pdf | Rechnung_2023-01_30071007000721.pdf | ok     |
| Rechnung_02_2023_30182074000721.pdf | Rechnung_2023-02_30182074000721.pdf | ok     |
| Rechnung_03_2023_30289101000721.pdf | Rechnung_2023-03_30289101000721.pdf | ok     |
| Rechnung_04_2023_30399641000721.pdf | Rechnung_2023-04_30399641000721.pdf | ok     |
| Rechnung_05_2023_30508276000721.pdf | Rechnung_2023-05_30508276000721.pdf | ok     |
| Rechnung_06_2023_30731561000721.pdf | Rechnung_2023-06_30731561000721.pdf | ok     |
└────────────────────────────────────────────────────────────────────────────────────┘
```

But I don't want the dash as separator. I want the underscore and it doesn't work for it?!
I tried to escape it by `$2\_$1`  but that didn't work too.

So, what am I doing wrong?

Fun fact, this exact behavior is reproduced by brenamer ... coincidence? or using some common libraries??

Best regards,
Teo

**Comment by teodias** [comment]
I cannot say why, but my entered text and the shown text is different.
I entered in my bug description " $ 2 _ $ 1 " without spaces, but in the preview  it shows "$2$1" eating the underscore ...

**Comment by ayoisaiah** [comment]
@teodias Thanks for reporting this! I will try to reproduce the issue and get back to you soon

**Comment by ixzh** [comment]
> I cannot say why, but my entered text and the shown text is different.

Because text between underscores are formatted as Italic, as shown from the second `(` to the last `2`. Put code in backticks.

**Comment by ayoisaiah** [comment]
Related to #32 

@teodias See [this comment](https://github.com/ayoisaiah/f2/issues/32#issuecomment-1358238673)

![image](https://github.com/ayoisaiah/f2/assets/13372163/52029db0-dc01-4355-930c-e0c186af49fc)
