### ISSUE TITLE
Cannot modify the file name of a file starting with '.' using .* matching?

### ISSUE THREAD

**Issue by BAKAOLC** [ayoisaiah/f2#46]
Environment: Windows 

Assuming there are several files in the same folder that are not hidden:

```
.01.png 01.png 02.png
```

So, using
```
F2 -f ".*" -r "{%02d}.png"
```

At this time, only the file names of `01.png` and `02.png` can be modified, and the file `.01.png` will not be renamed

Did I do something wrong?

**Comment by ayoisaiah** [comment]
Any file starting with `.` is regarded as hidden. Use the `-H` flag to include hidden files.

**Comment by BAKAOLC** [comment]
Okay, I can understand.

However, this may be a bit difficult for Windows users to accept, as the concealment of Windows is a separate attribute. Is there a preset distinction for this or is this behavior marked in the document?

**Comment by ayoisaiah** [comment]
You're right, hidden files are a different concept in Windows and we should not apply Linux conventions to Windows. I will consider changing the default behaviour in the next release

**Comment by ayoisaiah** [comment]
https://github.com/ayoisaiah/f2/commit/28a9278e32faf209d96ffbc06d02f44f63f1a15e
