### ISSUE TITLE
[Question] Custom when fix conflicts

### ISSUE THREAD

**Issue by haunt98** [ayoisaiah/f2#47]
For example currently fixing conflicts mean adding ` (2)`, ` (3)`, ... to filename

Can I change to `_01`, `_02`, ...

Because for some reason I don't want space in filename.

**Comment by ayoisaiah** [comment]
This is not possible right now, but I will consider adding this in the next release

**Comment by ayoisaiah** [comment]
@haunt98 I've added the `--fix-conflicts-pattern` flag so you can do something like:

```
f2 -r 'myfile.txt' -F --fix-conflicts-pattern '_%02d' 
```

This gives you _01, _02 etc. Please see the latest nightly

**Comment by haunt98** [comment]
I tried and it's looking good

<img width="473" alt="image" src="https://github.com/ayoisaiah/f2/assets/5424272/1b250b19-fcd0-44d0-a865-d81ba66ef256">


Thanks @ayoisaiah !

**Comment by haunt98** [comment]
Hi @ayoisaiah , I think there is an regression.

I try to run `f2 --replace "{mtime.YYYY}{mtime.MM}{mtime.DD}_{mtime.H}{mtime.mm}{mtime.ss}_{xt.ImageSize}{ext}" --fix-conflicts --fix-conflicts-pattern '_%02d' --exec` 2 times but the result is not the same.

<img width="1583" alt="image" src="https://github.com/ayoisaiah/f2/assets/5424272/913eedd6-dba6-44f3-b75d-9cd97d43fe3e">

Upper is first run, lower is second run.

**Comment by ayoisaiah** [comment]
It's fixed now:

![image](https://github.com/user-attachments/assets/46dc59b0-5692-4e88-9a91-6faa4f823931)

**Comment by haunt98** [comment]
Thanks @ayoisaiah :D
