### ISSUE TITLE
[discuss] should "Failed to match any files" be handled as an error or just a warning?

### ISSUE THREAD

**Issue by mo-han** [ayoisaiah/f2#5]
it is the exit code that matters
since f2 doesn't match any file, then setting the exit code to 1 is kind of "improper", and will disturb the following processes in a running script - case the script needs to check if f2 encountered any real error to determine how to do the next step
maybe just print that warning line, but without set the exit code, how's that?

**Comment by ayoisaiah** [comment]
That makes sense. It's not an error so it is indeed improper to exit with 1.

Fixed...will make a release soon, thanks! https://github.com/ayoisaiah/f2/commit/68f317a76697e7394ed2e0849463694f12e7aa57
