### ISSUE TITLE
How to order numbers ORIGINAL correctly, for example 1 2 3 4 5 6 7 8 9 10?

### ISSUE THREAD

**Issue by candrapersada** [ayoisaiah/f2#52]
How to order numbers correctly, for example `1 2 3 4 5 6 7 8 9 10`?
`f2 -r "Episode {%d}{ext}"`
![gambar](https://github.com/ayoisaiah/f2/assets/36833664/c3228f1f-94f9-413f-bee2-ae19f1161b7f)

**Comment by ayoisaiah** [comment]
@candrapersada Thanks for mentioning this! There's currently no way to sort numerically but it should be easy enough to add. I'm on it!

**Comment by ayoisaiah** [comment]
Fixed by https://github.com/ayoisaiah/f2/commit/f29aa03a8f1da4b1c451705a0c782543b07f263e

You can build from master to try it out. I'll make a new release later in the week 

![image](https://github.com/ayoisaiah/f2/assets/13372163/50df61f6-7828-4309-819f-4ab07679f64d)

**Comment by ayoisaiah** [comment]
You can also try a test it using a build here: https://github.com/ayoisaiah/f2/releases/tag/nightly

Thanks once again!

**Comment by candrapersada** [comment]
why f2 Nightly build windows 10
`f2 -r "Episode {%d}{ext}"`
`ERROR  The system cannot find the file specified.`

**Comment by ayoisaiah** [comment]
@candrapersada I've fixed the issue now, please use the latest nightly build
