### ISSUE TITLE
Substitute from list

### ISSUE THREAD

**Issue by joeldebruijn** [ayoisaiah/f2#53]
I'm looking for a way to search for patterns in filenames and replace/substitute them based on a list with patterns.
I read the documentation about CSV use and this issue: https://github.com/ayoisaiah/f2/issues/12

Context:
I'm coming from Windows with Advanced Renamer but I'm migrating to Linux, so looking for an alternative.
The use case is cleaning and replacing patterns in bulk exports of email.
In Thunderbird I use ImportExportNG to produce pdf in bulk.
The naming pattern is this: YYYYMMDD - HHMM - Sender mailadres - Subject

So I get files like:
20221216 - 091700 - play@google.come - Play -  De bevestiging van je Google Play-bestelling van 16 dec 2022.pdf
20230626 - 082704 - systeem@portabase.nl - Een nieuwe urenregistratie wacht op uw akkoord.pdf
20230829 - 202003 - noreply@dhlparcel.nl - Je pakket is bezorgd (3SMPK15563970)

I used 2 AREN files from Advanced Renamer:
- One to scrub all occurences of "RE", "Fwd", "Re", Camelcase everything and change other stuff postboxes do to subject naming when I reply.
- One to look up all senders: a list of actions applied to all files. For example, look for "- play@google.com -"  and replace it with "- Google - Play -", next look for "- systeem@portabase.nl -" and replace it with "- Portabase - Administratie -"

AFaik I can make F2 look for one pattern and execute one substitution on many files. But can it do this in batch?

Preferably with a csv with two columns? 

Like a csv with:
"- play@google.com -", "- Google - Play -"
"- systeem@portabase.nl - ", "- Portabase - Administratie -"
"- noreply@dhlparcel.nl -", "- DHL - Notification -"

Afaik the csv must have absolute name substitutions for the whole name and not dynamiccaly for parts or am I missing something?

**Comment by ayoisaiah** [comment]
@joeldebruijn Is this sort of what you're looking for?

![image](https://github.com/ayoisaiah/f2/assets/13372163/7ffb65bb-ca90-47c5-8208-49d34d76c3c5)

**Comment by joeldebruijn** [comment]
Yes! Thnx

But one concern, if the list of substitutes grows to about 200 items ...
and I string them together in 1 command ... doesnt that cause problems with the command line?

New to this, so dont know if parsing a 6000 character cmd is feasible?

**Comment by ayoisaiah** [comment]
@joeldebruijn It looks like there's a limit of 131k characters: https://serverfault.com/questions/163371/linux-command-line-character-limit

I'll look for a way to make this process easier perhaps using CSV files like you suggested.

**Comment by joeldebruijn** [comment]
131k will certainly be sufficient 😁👍

And if I "maintain" the command itself in a text editor I will get by in the meantime, thnx

**Comment by joeldebruijn** [comment]
If I can bother you one more time, I'm scratching my head about an hour now, after reading for example this:
https://www.baeldung.com/linux/run-multi-line-shell-code and many other StackExchange answers searching for "concatenation" or "continuation" of multiline commands.

I hoped to maintain the list in a text editor with \ or && or brackets like this, ommiting the linebreak so to say:

f2 \
-f '.*' -r '{f}{ext}'\
-f '- info@vanderfluit.nl -' -r '- van der Fluit - Info -'\
-f '- systeem@portabase.nl -' -r '- Portabase - Administratie -'\
-f ...

So ONE command using MANY arguments can be edited easily.
But pasted in the terminal I keep getting "-f bash command not found".

**Comment by ayoisaiah** [comment]
@joeldebruijn I believe you need a space before the backslash

```
f2 -f '.*' -r '{f}{ext}' \
-f '- info@vanderfluit.nl -' -r '- van der Fluit - Info -' \
-f '- info@blockchange.eu -' -r '- BlockChange - Info -' \
-f '- systeem@portabase.nl -' -r '- Portabase - Administratie -'
```

**Comment by joeldebruijn** [comment]
That .... did the trick, thanks!!!
Of course otherwise it cant distinguish between flags .....
Feel so stupid, but anyway learned a lot last hour.

Now I start migrating my old AdvancedRenamer workflow to F2, thnx!

**Comment by ayoisaiah** [comment]
Awesome! Do let me know if you run into other issues 🙂

**Comment by ixzh** [comment]
can options/flags accept no space? like `-f'pattern' -r'string'`. Would save a few spaces in a long command

**Comment by ayoisaiah** [comment]
@ixzh No this is not possible, you need a space between the options and their arguments

**Comment by joeldebruijn** [comment]
Must say, I get by using a spreadsheet with names of organisations / departments etc to calculate a F2 string by concatenation.
![afbeelding](https://github.com/ayoisaiah/f2/assets/3906940/2c1f3ef0-26ba-4c90-a0ad-93d51ca568b5)

Only thing is above approx 250 rows, pasting it in a terminal makes a bit ' funky'.
Because it cant display it right (Gnome Terminal).
Not really a blocking thing or something like that. I just paste it without looking and hit Enter. ;)

**Comment by joeldebruijn** [comment]
As a linux novice, suddenly remembered *.bat files from the early MS-DOS days. 
Learned that bash scripts exist with the same purpose. 

Now I have different sh files for groups of replacements (change timestamp convention, delete unwanted characters, replace mailadresses with organisations/names, remove my own mailadresses from the filename etc).

With the -V flag I even see the result and I dont have to paste 500 rows so to say,
