### ISSUE TITLE
Concatenate digits after a token number?

### ISSUE THREAD

**Issue by joeldebruijn** [ayoisaiah/f2#58]
I'm renaming with tokens and want to add numbers, for example:

f2 -f '(\d{4})-(\d{2})-(\d{2}) (\d{4})__(\d{8})_(\d{4}).gpx' -r '$5-$600.gpx' 

Use case:
- Timestampend GPX files from yyyy-mm-dd__yyyymmdd_hhmm to yyyymmdd_hhmmss
- The timestamp misses seconds so I want to add 00 for consistency.
- The 00 for seconds comes after token 6

Problem I think: Token nr 6 + characters 00 actually looks like token number 600.

Is there a way to concatenate 00 after a token number?

**Comment by msalbrain** [comment]
If this is still available, Would like to try it out

**Comment by msalbrain** [comment]
@joeldebruijn after checking the docs  I don't think that is possible. The best I got is adding a space or hyphen:

```bash

f2 -f '(\d{4})-(\d{2})-(\d{2}) (\d{4})__(\d{8})_(\d{4}).gpx' -r '$5-$6 00.gpx'

```

but I think having a simple character that escapes the `$6` will solve the problem like `-r '$5-$6/00.gpx'`.

**Comment by ayoisaiah** [comment]
@joeldebruijn @msalbrain 

This should do what you want:

```
f2 -f '(\d{4})-(\d{2})-(\d{2})__(\d{8})_(\d{4}).gpx' -r '$4-$5 00.gpx' -f ' '
```

![image](https://github.com/ayoisaiah/f2/assets/13372163/0ab22833-4560-47e2-af4c-84e18d9810c4)

Of course, you can use a different character instead of a space.

See: https://github.com/ayoisaiah/f2/wiki/F2-tutorial#chaining-renaming-operations

**Comment by joeldebruijn** [comment]
Subsequently adding a character and removing it, neat!
And lots of characters to choose from with small/zero chance being there in any other way.
Thnx!
