### ISSUE TITLE
Regex end matcher `$` not working

### ISSUE THREAD

**Issue by konsuko** [ayoisaiah/f2#59]
Hello,

following the documentation here: https://github.com/ayoisaiah/f2/wiki/Regular-expressions
The end matching of a file name with `$` as in the example `jpg$` does not work for me.

My full command is:
`f2 -f '_$' -r '' -R -d -x`

I would expect this to change the last character to empty if it's an underscore, but it does not match anything.

Here's my example file to match:
`my_cool_sound_file_.mp3`

**Comment by ayoisaiah** [comment]
You need to ignore file extensions with the `-e` flag:

![image](https://github.com/ayoisaiah/f2/assets/13372163/011ad0f1-27bb-4905-8702-83c45b6f424d)

**Comment by konsuko** [comment]
Thanks, it works perfectly now!
