### ISSUE TITLE
[Docs] The Wiki Uses Incorrect Syntax

### ISSUE THREAD

**Issue by ty114514** [ayoisaiah/f2#60]
https://github.com/ayoisaiah/f2/wiki/F2-tutorial#renaming-using-an-auto-incrementing-number

`f2 -f '.*\.' -r '%03d.'` -> `f2 -f '.*\.' -r '{%03d}.'`

Following [Renaming with an index](https://github.com/ayoisaiah/f2/wiki/Indexing), I think you forgot `{}`

: )

**Comment by joeldebruijn** [comment]
Can confirm, just yesterday tested it and at first it just puts %03d in the new filename, verbatim.

**Comment by ayoisaiah** [comment]
Thank you both, it's fixed now :pray:
