### ISSUE TITLE
--exclude fails to exclude directories

### ISSUE THREAD

**Issue by Pound-Hash** [ayoisaiah/f2#64]
Running `f2 FLAGS --include-dir --recursive --exclude DIRNAME` produces results that include files from DIRNAME.

Can we have this feature?

**Comment by ayoisaiah** [comment]
@Pound-Hash Thanks, I'll look into it

**Comment by ayoisaiah** [comment]
@Pound-Hash Please use the new `--exclude-dir` option (see latest nightly release)
