### ISSUE TITLE
[feature request] perhaps an option of "force overwrite" is needed in some cases

### ISSUE THREAD

**Issue by mo-han** [ayoisaiah/f2#7]
At least I'm eager for it, of course it should be served with conspicuous warnings and extra prompt.

**Comment by ayoisaiah** [comment]
@mo-han what's the use case is for overwriting files while renaming them? The `--fix-conflicts` option should remove the need for that no?

**Comment by mo-han** [comment]
use case is pretty simple:
1. run `f2` without `-x` and see the conflicts;
2. be sure all the conflicts are actually identical files;
3. so decide to overwrite them, not preserve duplicates.

**Comment by ayoisaiah** [comment]
Thanks for the clarification. I'll implement it and make a new release in a few hours.

**Comment by ayoisaiah** [comment]
![image](https://user-images.githubusercontent.com/13372163/119657648-1415b880-be24-11eb-93ee-fe5326113c6d.png)

Update to v1.6.5
