### ISSUE TITLE
Lost files when indexing from zero

### ISSUE THREAD

**Issue by gbmackenzie** [ayoisaiah/f2#72]
### Tick this box to confirm you have reviewed the above.

- [X] I've discovered a new issue with F2.

### What version of F2 are you using?

v1.9.1

### How did you install F2?

brew install

### What operating system are you using F2 on?

MacOS 14.4.1

### Describe your bug.

Renaming files using a zero-index causes files to be lost. (I had made a copy before renaming, so didn't lose any data personally!)

### What are the steps to reproduce the behavior?

```
➜  f2bug ls
01.txt 02.txt 03.txt
➜  f2bug f2 "\d\d" "{0%02d}"
*——————————*—————————*————————*
| ORIGINAL | RENAMED | STATUS |
*——————————*—————————*————————*
| 03.txt   | 02.txt  | ok     |
| 02.txt   | 01.txt  | ok     |
| 01.txt   | 00.txt  | ok     |
*——————————*—————————*————————*
 DRY RUN  Press ENTER to commit the above changes
➜  f2bug ls
00.txt
➜  f2bug f2 -u -x
*——————————*—————————*———————————————————————————*
| ORIGINAL | RENAMED |          STATUS           |
*——————————*—————————*———————————————————————————*
| 00.txt   | 01.txt  | ok                        |
| 02.txt   | 03.txt  | no such file or           |
|          |         | directory                 |
| 01.txt   | 02.txt  | no such file or           |
|          |         | directory                 |
*——————————*—————————*———————————————————————————*
 DRY RUN  Commit the above changes with the -x/--exec flag
 ERROR  reverting the renaming operation failed due to the above errors
```

### What behaviour did you observe?

Only `00.txt` is there. Two files have disappeared.

### What is the expected behaviour?

 I expected `00.txt`, `01.txt`, `02.txt`.

**Comment by gbmackenzie** [comment]
Note: I'm not sure if it was the zero-index that was causing this, I did not investigate. But I did not expect files being deleted to happen. At most there should be a conflict, but there wasn't even a conflict here.

**Comment by ayoisaiah** [comment]
The files were not sorted correctly and that's what caused the issue. I've now fixed the sorting problem but also added a way to detect such issues and report a conflict accordingly.

https://github.com/ayoisaiah/f2/commit/bc22222066598337157c683f161816374db422da
