### ISSUE TITLE
incorrect absolute path parsing inside of csv files on windows

### ISSUE THREAD

**Issue by broganeuquoixe** [ayoisaiah/f2#75]
### Tick this box to confirm you have reviewed the above.

- [X] I've discovered a new issue with F2.

### What version of F2 are you using?

1.9.1

### How did you install F2?

using [scoop](https://scoop.sh)
```pwsh
scoop install main/f2
```
which falls back to downloading the release from github https://github.com/ScoopInstaller/Main/blob/master/bucket/f2.json

### What operating system are you using F2 on?

Windows 11

### Describe your bug.

input.csv: (UTF-8)
```csv
C:/Users/user/Desktop/test/a/1.txt,../b/2.txt

```
file structure:
```tree
C:\Users\user\Desktop\test\
├─── a
│    └ 1.txt
├─── b
└─── input.csv
```

### What are the steps to reproduce the behavior?

with working directory = `C:\Users\user\Desktop\test\`
run `f2 --csv .\input.csv`

### What behaviour did you observe?

` ERROR  CreateFile C:\Users\user\Desktop\test\C:\Users\user\Desktop\test\a\1.txt: The filename, directory name, or volume label syntax is incorrect.`
The absolute path doesn't get parsed correctly

### What is the expected behaviour?

`1.txt` gets moved from `a/` into `b/` and gets renamed to `2.txt`

**Comment by ayoisaiah** [comment]
@broganeuquoixe Thanks a lot for reporting this! It's been fixed now, and will be included in the next release:

![image](https://github.com/user-attachments/assets/fb2540c6-ab8c-46f9-89b2-4414eb627493)

Please build from `master` to try it out.

**Comment by broganeuquoixe** [comment]
I've build the project from master and I can verify that this and the other issue have been fixed. Thank you!
