### ISSUE TITLE
Files with multiple extensions

### ISSUE THREAD

**Issue by muzimuzhi** [ayoisaiah/f2#79]
#### Describe your feature request

In `f2` v1.9.1, the `{ext}` variable for file extension only holds everything starting from the final dot in filename. This works in most cases but not when renaming files with multiple/nested extensions.

```
$ touch file.tar.gz
$ f2 -f '.*\.gz$' -r 'a{ext}'
*—————————————*—————————*————————*
|  ORIGINAL   | RENAMED | STATUS |
*—————————————*—————————*————————*
| file.tar.gz | a.gz    | ok     |
*—————————————*—————————*————————*
 DRY RUN  Commit the above changes with the -x/--exec flag
```

A new command-line option like `--multiple-ext` may help.

**Comment by ayoisaiah** [comment]
Added: https://github.com/ayoisaiah/f2/commit/1a1c14856de2eaaf113ce784aa8eab4089b9c12e

Use `{2ext}`:

![image](https://github.com/user-attachments/assets/2f0b43b7-603c-4a73-9be7-cd70fd943019)

**Comment by muzimuzhi** [comment]
Many thanks!
