### ISSUE TITLE
[bug] error when double dots ".." in sub-folder (of dst path)

### ISSUE THREAD

**Issue by mo-han** [ayoisaiah/f2#8]
I'm using f2 to group lots of files into sub-folders based on part of their names, via regex. When renameing is something like from src `/root/title [artist_name_with..].mp4` to dst `/root/artist_name_with../title [artist_name_with..].mp4`, it throws `an error occurred while renaming`. Could only guess but seems like the double dots `..` in the sub-folder name `artist_name_with..` is the cause.

OS is Windows 10

**Comment by ayoisaiah** [comment]
The root of the problem appears to be the automatic stripping of trailing dots from a file or directory name, so the `artist_name_with..` directory will be created as `artist_name_with`. The program subsequently tries to rename the file as `artist_name_with../<filename>` but that path will not be found leading to the error.

**Comment by ayoisaiah** [comment]
When I forcibly create a directory that has trailing dots (through [this workaround](https://stackoverflow.com/a/17098082)), the file explorer still strips the trailing dots leading to a location not found message

![image](https://user-images.githubusercontent.com/13372163/118402578-699ed800-b662-11eb-85d8-d8344f5885f9.png)

**Comment by ayoisaiah** [comment]
I think the solution to this is to raise a conflict when this situation occurs, so that the renaming operation does not proceed until it is resolved. The `--fix-conflicts` option will auto remove all trailing dots.

**Comment by ayoisaiah** [comment]
Fix is now live in v1.6.2.
