### ISSUE TITLE
The variable F2_DEFAULT_OPTS doesn't work

### ISSUE THREAD

**Issue by bound-variable** [ayoisaiah/f2#81]
### Tick this box to confirm you have reviewed the above.

- [X] I've discovered a new issue with F2.

### What version of F2 are you using?

F2 version v1.9.1

### How did you install F2?

Go

### What operating system are you using F2 on?

Gentoo

### Describe your bug.

Exporting an assignment of `--no-color` or `--interactive` or `-n` to the variable F2_DEFAULT_OPTS fails to load these options as defaults.

### What are the steps to reproduce the behavior?

Write `export F2_DEFAULT_OPTS="--interactive"` in my bashrc (or anywhere else to export it)

### What behaviour did you observe?

No changes in default behavior. However, the variable F2_NO_COLOR does work: `export F2_NO_COLOR=true`

### What is the expected behaviour?

Default options should apply

**Comment by ayoisaiah** [comment]
@bound-variable Can you please install from `master` and confirm if the behavior you're describing is still present?

**Comment by bound-variable** [comment]
I had installed it via `go install github.com/ayoisaiah/f2/cmd/f2@latest`

How do I install it from master?

**Comment by ayoisaiah** [comment]
@bound-variable You can use the nightly build: https://github.com/ayoisaiah/f2/releases/tag/nightly

**Comment by bound-variable** [comment]
The variable works in the prebuilt package: `f2_master_linux_amd64.tar.gz`

**Comment by ayoisaiah** [comment]
@bound-variable Great! I'll be releasing a new version in the coming days
