### ISSUE TITLE
The --ignore-ext should ignore only the extension, not everything after the first dot

### ISSUE THREAD

**Issue by bound-variable** [ayoisaiah/f2#82]
When I use the option `--ignore-ext` everything after a first dot `.` is ignored, but it would be better if only the extension were ignored.

**Comment by ayoisaiah** [comment]
@bound-variable Can you please share an example? `--ignore-ext` only ignores file extensions from the final dot:

```
f2 -r "{%03d}" --ignore-ext index.controller.js
*—————————————————————*—————————*————————*
|      ORIGINAL       | RENAMED | STATUS |
*—————————————————————*—————————*————————*
| index.controller.js | 001.js  | ok     |
*—————————————————————*—————————*————————*
```

**Comment by bound-variable** [comment]
Sorry, I think I got confused somewhere last night. Nevermind.
